mode: "sample"  # "train" or "sample"
N: 28 # amino acid alphabet size
max_length: 30
device: "cuda:0"

output_path: "sampled_amps_1000.fasta"
num_samples: 1000
batch_size: 128
num_train_epochs: 50
eval_every: 900
lr: 2e-4
save_dir: "ckpt_amp"
checkpoint_path: "ckpt_amp/d3pm_amp.pth"
wandb_project: "d3pm_amp"
hybrid_loss_coeff: 0.001
n_T: 1000
data_path: "data/data.fasta"
